---
title: ZARMS - Database Schema
---

erDiagram
    logs {
        uuid id PK "ログID"
        varchar operation_type_key "操作タイプキー"
        varchar table_name "テーブル名"
        varchar record_id "レコードID"
        text data "記録されたデータ"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
    }
    boards {
        uuid id PK "ボードID"
        int display_id "ボードID(連番)"
        varchar email "メールアドレス"
        varchar name "ボード名"
        text description "ボード説明"
        boolean is_active "有効"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    comments {
        uuid id PK "コメントID"
        int display_id "コメントID(連番)"
        text content "コメント内容"
        uuid mentioned_to "メンション先"
        varchar related_table "関連テーブル"
        uuid related_id "関連ID"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    directories {
        uuid id PK "組織ID"
        int display_id "組織ID(連番)"
        uuid parent_directory_id "親組織ID"
        varchar directory_type_key "組織タイプキー"
        varchar name "組織名: 企画応募フォーム：代表者の所属する団体・コミュニティ名"
        varchar slack_channel_url "SlackチャンネルURL: 企画応募フォーム: これまでの活動の実態・実績がわかるようなSlackチャンネル"
        varchar gfolder_id "フォルダID"
        boolean is_active "有効"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    apps {
        uuid id PK "アプリID"
        varchar name "アプリ名"
        varchar url "アプリURL"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    members {
        uuid id PK "メンバーID"
        varchar email "メールアドレス"
        varchar slack_profile_url "SlackプロフィールURL"
        varchar name "氏名"
        varchar display_name "表示名"
        varchar profile_photo_url "プロフィール写真URL"
        boolean is_active "有効"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    plan_assignments {
        uuid id PK "企画割り当てID"
        uuid plan_id "企画ID"
        uuid member_id "メンバーID"
        varchar role "役割"
        boolean is_active "有効"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    directory_assignments {
        uuid id PK "組織割り当てID"
        uuid directory_id "組織ID"
        uuid member_id "メンバーID"
        varchar role "役割"
        boolean is_active "有効"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    tasks {
        uuid id PK "タスクID"
        int display_id "タスクID(連番)"
        uuid parent_task_id "親タスクID"
        uuid board_id "ボードID"
        varchar name "タスク名"
        text description "タスク説明"
        datetime starts_at "開始日時"
        datetime ends_at "終了日時"
        varchar task_status_key "タスクステータスキー"
        varchar priority_key "優先度キー"
        uuid processed_by "進行者"
        uuid reviewed_by "確認者"
        uuid received_by "受領者"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    lists {
        uuid id PK "リストID"
        int index "インデックス"
        uuid task_id "タスクID"
        boolean is_done "完了"
        varchar name "リスト名"
        uuid assign_to "割り当て先"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    links {
        uuid id PK "リンクID"
        int index "インデックス"
        uuid task_id "タスクID"
        varchar label "ラベル"
        varchar url "URL"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    files {
        uuid id PK "ファイルID"
        int index "インデックス"
        uuid task_id "タスクID"
        varchar gfile_id "ファイルID"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    system_updates {
        uuid id PK "アップデートID"
        varchar version "バージョン番号"
        varchar title "アップデートタイトル"
        text description "アップデート内容"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    questions {
        uuid id PK "問い合わせID"
        varchar question_number "問い合わせ番号"
        datetime created_at "作成日時"
        varchar question_category "問い合わせカテゴリー"
        text question_content "問い合わせ内容"
        text remark "システム備考"
        uuid created_by "作成者"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    plans {
        uuid id PK "企画ID"
        varchar plan_number "企画番号"
        varchar zarms_code "ZARMSコード"
        uuid parent_plan_number "親企画番号"
        int plan_type_sequence_number "企画種別内連番"
        varchar plan_status "企画状態"
        varchar plan_type "企画種別"
        varchar name "企画名"
        varchar summary "企画概要"
        text description "企画説明"
        text plan_tags "企画タグ"
        text plan_categories "企画カテゴリー"
        text selection_application_text "選考応募文"
        varchar selection_presentation_url "選考プレゼン動画URL"
        text first_selection_comment "一次選考コメント"
        text second_selection_comment "二次選考コメント"
        int estimated_staff_count "推定運営者数"
        int estimated_participant_count "推定参加者数"
        int estimated_total_cost "推定合計費用"
        int actual_staff_count "実績運営者数"
        int actual_participant_count "実績参加者数"
        int actual_total_cost "実績合計費用"
        boolean has_collaborators "学外連携組織情報あり"
        boolean has_guests "ゲスト情報あり"
        varchar online_media_type "オンライン媒体種別"
        varchar online_media_url "オンライン媒体URL"
        varchar website_url "特設サイトURL"
        varchar sheet_url "シートURL"
        varchar folder_url "フォルダURL"
        varchar document_url "ドキュメントURL"
        varchar slide_url "スライドURL"
        varchar script_url "台本URL"
        varchar thumbnail_url "サムネイルURL"
        varchar exhibitor_type "出展者種別"
        varchar exhibitor_member "出展代表者"
        varchar exhibitor_directory "出展団体"
        varchar manager_committee_student "管理代表者"
        varchar manager_committee_staff "管理団体"
        varchar slack_channel_url "SlackチャンネルURL"
        boolean has_recruitment "募集情報あり"
        boolean has_live "生放送あり"
        text remark "システム備考"
        uuid applied_by "応募者"
        datetime applied_at "応募日時"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
        copyright_application_form1_submitted "著作物利用申請フォーム1提出"
        copyright_application_form2_submitted "著作物利用申請フォーム2提出"
        copyright_application_form3_submitted "著作物利用申請フォーム3提出"
        copyright_application_form4_submitted "著作物利用申請フォーム4提出"
        copyright_application_form5_submitted "著作物利用申請フォーム5提出"
        ai_usage "AI利用備考"
    }
    logs }|--|| members : "created_by"
    apps }|--|| members : "created_by"
    apps }|--|| members : "updated_by"
    boards }|--|| members : "created_by"
    boards }|--|| members : "updated_by"
    comments }|--|| boards : "mentioned_to"
    comments }|--|| members : "created_by"
    comments }|--|| members : "updated_by"
    directories }|--|| directories : "parent_directory_id"
    directories }|--|| members : "created_by"
    directories }|--|| members : "updated_by"
    links }|--|| tasks : "task_id"
    links }|--|| members : "created_by"
    links }|--|| members : "updated_by"
    members }|--|| members : "created_by"
    members }|--|| members : "updated_by"
    plan_assignments }|--|| plans : "plan_id"
    plan_assignments }|--|| members : "member_id"
    plan_assignments }|--|| members : "created_by"
    plan_assignments }|--|| members : "updated_by"
    directory_assignments }|--|| directories : "directory_id"
    directory_assignments }|--|| members : "member_id"
    directory_assignments }|--|| members : "created_by"
    directory_assignments }|--|| members : "updated_by"
    tasks }|--|| tasks : "parent_task_id"
    tasks }|--|| members : "processed_by"
    tasks }|--|| members : "reviewed_by"
    tasks }|--|| members : "received_by"
    tasks }|--|| members : "created_by"
    tasks }|--|| members : "updated_by"
    lists }|--|| tasks : "task_id"
    lists }|--|| members : "assign_to"
    lists }|--|| members : "created_by"
    lists }|--|| members : "updated_by"
    files }|--|| tasks : "task_id"
    files }|--|| members : "created_by"
    files }|--|| members : "updated_by"
    system_updates }|--|| members : "created_by"
    system_updates }|--|| members : "updated_by"
    questions }|--|| members : "created_by"
    questions }|--|| members : "updated_by"