---
title: ZARMS Database Schema
---

erDiagram
    CONFIG {
        serial id PK "設定ID"
        int parent_config_id "親設定ID"
        varchar type "タイプ"
        varchar key "キー"
        varchar value "値"
        text remark "システム備考"
        boolean is_preset "プリセット"
        boolean is_active "有効"
        int sort_order "並び順"
    }
    ENUM {
        varchar key PK "キー"
        varchar parent_key "親キー"
        varchar value "値"
        text remark "システム備考"
        boolean is_preset "プリセット"
        boolean is_active "有効"
        int sort_order "並び順"
        datetime created_at "作成日時"
    }
    logs {
        uuid log PK "ログID"
        varchar log_type_key "操作タイプキー"
        varchar table_name "テーブル名"
        varchar record_id "レコードID"
        varchar column_name "カラムID"
        text old_value "変更前の値"
        text new_value "変更後の値"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    assignments {
        uuid id PK "割り当てID"
        varchar table_from "割り当て元テーブル"
        uuid id_from "割り当て元ID"
        varchar table_to "割り当て先テーブル"
        uuid id_to "割り当て先ID"
        text remark "システム備考"
        boolean is_active "有効"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    advertisements {
        uuid id PK "広告ID"
        serial display_id "広告ID(シリアル)"
        varchar advertisement_status_key "広告ステータスキー"
        varchar advertisement_type_key "広告タイプキー"
        uuid medium_id "投稿先"
        varchar title "広告タイトル"
        text body "広告本文"
        varchar gfolder_id "添付フォルダID"
        text remark "システム備考"
        boolean is_deleted
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    attendances {
        uuid id PK "出欠ID"
        uuid event_id "イベントID"
        boolean is_required "招待タイプ: falseの場合は、gcalendar上でoptionalとしてマークされる"
        varchar attendance_type_key "出席タイプキー"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    budgets {
        uuid id PK
        serial display_id
        uuid plan_id
        uuid requesting_directory_id
        uuid managing_directory_id
        varchar priority_key
        varchar budget_status_key
        varchar budget_type_key
        int amount
        text purpose "用途"
        text remark "システム備考"
        uuid created_by
        datetime created_at
        uuid updated_by
        datetime updated_at
    }
    creatives {
        uuid id PK "制作物ID"
        serial display_id "制作物ID(シリアル)"
        uuid plan_id "企画ID"
        uuid advertisement_id "広告ID"
        varchar title "制作物タイトル"
        varchar creative_status_key "制作物ステータスキー"
        varchar creative_type_key "制作物タイプキー"
        varchar priority_key "優先度キー"
        datetime deadline_at "期限日時"
        uuid client_directory_id "依頼元組織ID"
        int deliverable_count "成果物数"
        varchar gfolder_id "フォルダID"
        varchar document_gfile_id "ドキュメントファイルID"
        varchar document_gtab_id "ドキュメントタブID"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    directories {
        uuid id PK "組織ID"
        serial display_id "組織ID(シリアル)"
        uuid parent_directory_id "親組織ID"
        varchar directory_type_key "組織タイプキー"
        varchar name "組織名: 企画応募フォーム：代表者の所属する団体・コミュニティ名"
        text summary "組織概要: 企画応募フォーム：どのような団体／コミュニティでの応募ですか？"
        text description "組織説明: 企画応募フォーム：その他、これまでの活動実績についてアピールポイント"
        varchar slack_channel_url "SlackチャンネルURL: 企画応募フォーム: これまでの活動の実態・実績がわかるようなSlackチャンネル"
        varchar document_gfile_id "ドキュメントID"
        varchar gfolder_id "フォルダID"
        text remark "システム備考"
        boolean is_active "有効"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    events {
        uuid id PK "イベントID"
        serial display_id "イベントID"
        varchar ical_id "イベントID(iCal): Google カレンダーから取得"
        uuid owner_directory_id "主催組織ID"
        varchar calendar_id "カレンダーID: どのGoogle カレンダーに登録するか"
        uuid plan_id "企画ID"
        varchar title "イベントタイトル"
        text description "イベント概要"
        varchar location "イベント場所"
        date start_date "イベント開始日"
        time start_time "イベント開始時刻"
        date end_date "イベント終了日"
        time end_time "イベント終了時刻"
        varchar event_type_key "イベントタイプキー"
        varchar event_color_key "イベント色キー"
        boolean is_visible "公開"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    expenses {
        uuid id PK
        uuid budget_id
        varchar expense_status_key "支払い・精算状況"
        varchar expense_type_key "支出勘定科目"
        varchar title
        int amount
        varchar receipt_gfile_id "領収書のファイルID"
        varchar invoice_gfile_id "請求書のファイルID"
        text description
        text remark "システム備考"
        date paid_at "支払い発生日"
        uuid paid_by "支払担当者: 原則created_byと同一"
        datetime created_at
        uuid created_by
        datetime updated_at
        uuid updated_by
    }
    forms {
        uuid id PK "フォームID"
        serial display_id "フォームID(シリアル)"
        varchar gfile_id "Google ドライブのファイルID"
        varchar title "公開フォームのタイトル"
        text description "説明"
        varchar destination_gfile_id "スプレッドシートのID"
        varchar edit_url "編集URL"
        varchar summary_url "概要URL(編集画面)"
        varchar published_url "回答URL(長い)"
        boolean can_edit_response "回答を編集可能か"
        boolean is_email_collected "メールアドレスの収集"
        text confirmation_message "回答送信後のメッセージ"
        text closed_form_message "回答受付期間外のメッセージ"
        int limit_response_per_form "フォーム全体の回答数の上限（到達したら自動で回答締切）"
        int limit_response_per_user "1ユーザー1回までの送信制限"
        boolean is_published "フォームを公開しているか"
        boolean is_accepting_response "フォームの回答を受け付けているか"
        boolean has_respond_again_link "回答終了後に別の回答を送信のリンクを表示するか"
        boolean is_publishing_summary "回答の概要を公開しているか"
        datetime starts_publishing_at
        datetime ends_publishing_at
        datetime starts_accepting_response_at
        datetime ends_accepting_response_at
        text remark "システム備考"
        boolean is_deleted
        uuid created_by "作成者: フォームの作成者"
        datetime created_at "作成日時: フォームの作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    hardwares {
        uuid id PK "備品ID"
        serial display_id "備品ID(シリアル)"
        varchar hardware_type_key "カテゴリー"
        varchar name "備品名"
        text description "説明"
        int quantity "数量"
        uuid managing_directory_id "管理組織"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    jobs {
        uuid id PK "仕事ID"
        serial display_id "仕事ID(シリアル)"
        varchar job_type_id "仕事タイプ"
        uuid managing_directory_id "管轄組織"
        varchar title "タイトル"
        text place "集合場所"
        text description "仕事説明"
        int duration_minutes_min "最大労働時間"
        text time_period_option "募集時間帯"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    knowledges {
        uuid id PK "思考ID"
        serial display_id "思考ID(シリアル)"
        varchar knowledge_type_key "思考タイプキー"
        varchar title "思考タイトル"
        text description "思考詳細"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    licenses {
        uuid id PK "ID: 一意の識別子"
        serial display_id "ID(シリアル): 一意の識別子"
        varchar service_name "サービス名: 例: Adobe Stock, Unsplash, DOVA-SYNDROME"
        varchar plan_type "契約プラン: 法人プラン / 個人プラン / 無料枠 等"
        varchar site_url "サイトURL: サービスのトップページまたはログインページ"
        varchar terms_url "利用規約URL: 規約ページのURL(規約変更時に確認するため)"
        varchar commercial_detail "商用利用: 商用利用が可能かどうかのフラグ"
        varchar modification_detail "加工可否: 素材の加工が許可されているか"
        varchar attribution_detail "クレジット表記要否: クレジット表記が必要かどうか"
        text attribution_text "クレジット表記文言: 実際に記載すべき著作者名やURL(コピペ用)"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    mediums {
        uuid id PK "媒体ID"
        varchar title "媒体名"
        text description "媒体詳細"
        varchar site_url "媒体URL"
        varchar managing_directory_id "管理組織ID"
        varchar visibility_directory_id "公開先組織ID"
        varchar account_handle "アカウントハンドル"
        varchar medium_status_key "運用ステータスキー"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    members {
        uuid id PK "メンバーID"
        varchar email "メールアドレス"
        varchar profile "プロフィールURL: 原則SlackプロフィールのURLを入力"
        varchar nickname "ニックネーム: 原則Slack表示名を入力"
        varchar nickname_yomi "ニックネーム（よみ）"
        varchar last_name "姓"
        varchar last_name_yomi "姓（よみ）"
        varchar first_name "名"
        varchar first_name_yomi "名（よみ）"
        int phone_number "電話番号"
        boolean is_staff_day0 "Day0スタッフ"
        boolean is_staff_day1 "Day1スタッフ"
        boolean is_staff_day2 "Day2スタッフ"
        varchar system_role_key "システムロールキー"
        varchar portfolio_url "ポートフォリオ"
        varchar icon_gfile_id "アイコンファイルID"
        boolean is_active "有効"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    member_assignments {
        uuid id PK "割り当てID"
        uuid member_id "メンバーID"
        varchar related_table "割り当て先テーブル: creatives/shifts/directories"
        uuid related_id "割り当て先ID"
        text remark "システム備考"
        boolean is_active "有効"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    merchandises {
        uuid id PK "製品ID"
        serial display_id "製品ID(シリアル)"
        varchar merchandise_status_key "商品ステータスキー"
        varchar title "製品タイトル"
        text description "製品詳細"
        int price "製品価格: 税抜"
        int price_label "製品価格備考: 何個何円、とか"
        float price_tax_rate "消費税率: 百分率"
        varchar model_number "製品型番"
        int deliverable_count "納品数"
        uuid plan_id "企画ID"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    musics {
        uuid id PK "楽曲ID"
        varchar music_status_key "楽曲審査ステータスキー"
        varchar title "楽曲タイトル"
        varchar artist_name "アーティスト名"
        varchar lyricist_name "作詞者名"
        varchar composer_name "作曲者名"
        uuid plan_id "企画ID"
        varchar audio_url "音源URL（ダウンロード元サイト）"
        boolean is_used "実際に使用したか"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    notes {
        uuid id PK "コメントID"
        text content "コメント内容"
        uuid mentioned_to "メンション先"
        varchar related_table "該当テーブル"
        uuid related_id "該当レコードID"
        boolean is_deleted "コメントが削除済みか"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    plans {
        uuid id PK "企画ID"
        serial display_id "企画ID(シリアル)"
        varchar plan_status_key "企画ステータスキー"
        varchar title "企画名"
        text description "企画概要"
        varchar guest_invitation_status_key "ゲスト招待ステータスキー"
        text guest_detail "ゲスト詳細"
        varchar external_collaboration_status_key "外部連携ステータスキー"
        text external_detail "外部連携詳細"
        varchar expected_operators "運営者数（見込）"
        varchar expected_entries "参加者数（見込）"
        varchar actual_operators "運営者数（実績）"
        varchar actual_entries "参加者数（実績）"
        int dur_minutes "所要分数: 企画応募時の回答内容を反映（ステージ企画）"
        float dur_days "所要日数: 企画応募時の回答内容を反映（ブース企画）"
        varchar sale_status_key "物販ステータスキー"
        varchar folder_id "フォルダID"
        varchar thumbnail_file_id "サムネイルファイルID"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    questions {
        uuid id PK "問い合わせID"
        serial display_id "問い合わせID(シリアル)"
        varchar question_status_key "問い合わせステータス"
        text question_content "問い合わせ内容"
        text answer_content "回答内容"
        uuid questioned_org_id "問い合わせ元組織: 一般の参加者等の場合はNULL?"
        uuid answered_org_id "回答元組織"
        datetime opened_at "質問投稿日"
        datetime closed_at "回答終了日"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    resources {
        uuid id PK "リソースID"
        serial display_id "リソースID(シリアル)"
        varchar resource_type_key
        varchar url
        varchar title
        text description
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    shifts {
        uuid id PK "シフトID"
        uuid job_id "仕事ID"
        datetime starts_at "開始日時"
        datetime ends_at "終了日時"
        text description "説明"
        int recruiting_count "募集人数"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    skills {
        uuid id PK "スキルID"
        varchar skill_type_key "スキルタイプキー"
        varchar title "スキル名"
        text description "スキル説明"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    tasks {
        uuid id PK "タスクID"
        serial display_id "タスクID(シリアル)"
        uuid parent_task_id "親タスクID"
        varchar task_status_key "タスクステータスキー"
        varchar title "タスクタイトル"
        text description "タスク概要"
        varchar priority_key "優先度キー"
        uuid assign_to "担当者"
        datetime starts_at "開始日時"
        datetime ends_at "終了日時"
        boolean is_deleted "削除済みか"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    timetracks {
        uuid id PK "勤怠ID"
        uuid member_id "メンバーID"
        datetime started_at "開始日時"
        datetime ended_at "終了日時"
        text remark "システム備考"
        boolean is_deleted "勤怠が削除済みか"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    wikis {
        uuid id PK "ウィキID"
        serial display_id "ウィキID(シリアル)"
        varchar wiki_status_key "ウィキステータスキー"
        varchar title
        text content "notionのようなブロックエディタ"
        text remark "システム備考"
        uuid created_by "作成者"
        datetime created_at "作成日時"
        uuid updated_by "最終更新者"
        datetime updated_at "最終更新日時"
    }
    ENUM }|--|| ENUM : "parent_key"
    logs }|--|| ENUM : "log_type_key"
    advertisements }|--|| ENUM : "advertisement_status_key"
    advertisements }|--|| ENUM : "advertisement_type_key"
    attendances }|--|| ENUM : "attendance_type_key"
    budgets }|--|| ENUM : "priority_key"
    budgets }|--|| ENUM : "budget_status_key"
    budgets }|--|| ENUM : "budget_type_key"
    creatives }|--|| ENUM : "creative_status_key"
    creatives }|--|| ENUM : "creative_type_key"
    creatives }|--|| ENUM : "priority_key"
    directories }|--|| ENUM : "directory_type_key"
    events }|--|| ENUM : "event_type_key"
    events }|--|| ENUM : "event_color_key"
    expenses }|--|| ENUM : "expense_status_key"
    expenses }|--|| ENUM : "expense_type_key"
    hardwares }|--|| ENUM : "hardware_type_key"
    knowledges }|--|| ENUM : "knowledge_type_key"
    mediums }|--|| ENUM : "medium_status_key"
    members }|--|| ENUM : "system_role_key"
    musics }|--|| ENUM : "music_status_key"
    plans }|--|| ENUM : "plan_status_key"
    plans }|--|| ENUM : "guest_invitation_status_key"
    plans }|--|| ENUM : "external_collaboration_status_key"
    plans }|--|| ENUM : "sale_status_key"
    questions }|--|| ENUM : "question_status_key"
    skills }|--|| ENUM : "skill_type_key"
    tasks }|--|| ENUM : "task_status_key"
    tasks }|--|| ENUM : "priority_key"
    logs }|--|| members : "created_by"
    logs }|--|| members : "updated_by"
    assignments }|--|| members : "created_by"
    assignments }|--|| members : "updated_by"
    advertisements }|--|| mediums : "medium_id"
    advertisements }|--|| members : "created_by"
    advertisements }|--|| members : "updated_by"
    attendances }|--|| events : "event_id"
    attendances }|--|| members : "created_by"
    attendances }|--|| members : "updated_by"
    budgets }|--|| plans : "plan_id"
    budgets }|--|| directories : "requesting_directory_id"
    budgets }|--|| directories : "managing_directory_id"
    budgets }|--|| members : "created_by"
    budgets }|--|| members : "updated_by"
    creatives }|--|| plans : "plan_id"
    creatives }|--|| advertisements : "advertisement_id"
    creatives }|--|| directories : "client_directory_id"
    creatives }|--|| members : "client_member_id"
    creatives }|--|| members : "created_by"
    creatives }|--|| members : "updated_by"
    directories }|--|| directories : "parent_directory_id"
    directories }|--|| members : "created_by"
    directories }|--|| members : "updated_by"
    events }|--|| directories : "owner_directory_id"
    events }|--|| plans : "plan_id"
    events }|--|| members : "created_by"
    events }|--|| members : "updated_by"
    expenses }|--|| budgets : "budget_id"
    expenses }|--|| members : "paid_by"
    expenses }|--|| members : "created_by"
    expenses }|--|| members : "updated_by"
    forms }|--|| members : "created_by"
    forms }|--|| members : "updated_by"
    hardwares }|--|| directories : "managing_directory_id"
    hardwares }|--|| members : "created_by"
    hardwares }|--|| members : "updated_by"
    knowledges }|--|| members : "created_by"
    knowledges }|--|| members : "updated_by"
    licenses }|--|| members : "created_by"
    licenses }|--|| members : "updated_by"
    mediums }|--|| directories : "managing_directory_id"
    mediums }|--|| directories : "visibility_directory_id"
    mediums }|--|| members : "created_by"
    mediums }|--|| members : "updated_by"
    members }|--|| members : "created_by"
    members }|--|| members : "updated_by"
    member_assignments }|--|| members : "member_id"
    member_assignments }|--|| members : "created_by"
    member_assignments }|--|| members : "updated_by"
    merchandises }|--|| plans : "plan_id"
    merchandises }|--|| members : "created_by"
    merchandises }|--|| members : "updated_by"
    musics }|--|| plans : "plan_id"
    musics }|--|| members : "created_by"
    musics }|--|| members : "updated_by"
    notes }|--|| members : "mentioned_to"
    notes }|--|| members : "created_by"
    notes }|--|| members : "updated_by"
    plans }|--|| members : "created_by"
    plans }|--|| members : "updated_by"
    questions }|--|| directories : "questioned_org_id"
    questions }|--|| directories : "answered_org_id"
    questions }|--|| members : "created_by"
    questions }|--|| members : "updated_by"
    resources }|--|| members : "created_by"
    resources }|--|| members : "updated_by"
    shifts }|--|| jobs : "job_id"
    shifts }|--|| members : "created_by"
    shifts }|--|| members : "updated_by"
    skills }|--|| members : "created_by"
    skills }|--|| members : "updated_by"
    tasks }|--|| tasks : "parent_task_id"
    tasks }|--|| members : "assign_to"
    tasks }|--|| members : "created_by"
    tasks }|--|| members : "updated_by"
    timetracks }|--|| members : "member_id"
    timetracks }|--|| members : "created_by"
    timetracks }|--|| members : "updated_by"
    wikis }|--|| members : "created_by"
    wikis }|--|| members : "updated_by"
